# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ToDo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ToDo

  # Fetch sources from local development pod if you have one
  pod 'TDRedux.swift', :path => '~/proj/TDRedux.swift'

  # Fetch sources from GitHub
  # pod 'TDRedux.swift', '~> 1.0'
end
